In [ ]:
import pandas as pd
import numpy as np

LABELS = ['label_1', 'label_2', 'label_3', 'label_4']
FEATURES = ['feature_'+ str(i) for i in range(1,257)]

In [ ]:
train = pd.read_csv("drive/MyDrive/Colab Notebooks/Lab 1/train.csv")
valid = pd.read_csv("drive/MyDrive/Colab Notebooks/Lab 1/valid.csv")
test = pd.read_csv("drive/MyDrive/Colab Notebooks/Lab 1/test.csv")

In [ ]:
print(LABELS)
print(FEATURES)

['label_1', 'label_2', 'label_3', 'label_4']
['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19', 'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24', 'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29', 'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34', 'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39', 'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44', 'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49', 'feature_50', 'feature_51', 'feature_52', 'feature_53', 'feature_54', 'feature_55', 'feature_56', 'feature_57', 'feature_58', 'feature_59', 'feature_60', 'feature_61', 'feature_62', 'feature_63', 'feature_64', 'feature_65', 'feature_66', 'feature_67', 'feature_68', 'feature_69', 'feature_70', 'feature_71', 'feature_72', 'feature_73', 'feature_74', 'feature_75', 'feature_76', 'feature_77', 'feature_78', 'feature_79', 'feature_80', 'feature_81', 'feature_82', 'feature_83', 'feature_84', 'feature_85', 'feature_86', 'feature_87', 'feature_88', 'feature_89', 'feature_90', 'feature_91', 'feature_92', 'feature_93', 'feature_94', 'feature_95', 'feature_96', 'feature_97', 'feature_98', 'feature_99', 'feature_100', 'feature_101', 'feature_102', 'feature_103', 'feature_104', 'feature_105', 'feature_106', 'feature_107', 'feature_108', 'feature_109', 'feature_110', 'feature_111', 'feature_112', 'feature_113', 'feature_114', 'feature_115', 'feature_116', 'feature_117', 'feature_118', 'feature_119', 'feature_120', 'feature_121', 'feature_122', 'feature_123', 'feature_124', 'feature_125', 'feature_126', 'feature_127', 'feature_128', 'feature_129', 'feature_130', 'feature_131', 'feature_132', 'feature_133', 'feature_134', 'feature_135', 'feature_136', 'feature_137', 'feature_138', 'feature_139', 'feature_140', 'feature_141', 'feature_142', 'feature_143', 'feature_144', 'feature_145', 'feature_146', 'feature_147', 'feature_148', 'feature_149', 'feature_150', 'feature_151', 'feature_152', 'feature_153', 'feature_154', 'feature_155', 'feature_156', 'feature_157', 'feature_158', 'feature_159', 'feature_160', 'feature_161', 'feature_162', 'feature_163', 'feature_164', 'feature_165', 'feature_166', 'feature_167', 'feature_168', 'feature_169', 'feature_170', 'feature_171', 'feature_172', 'feature_173', 'feature_174', 'feature_175', 'feature_176', 'feature_177', 'feature_178', 'feature_179', 'feature_180', 'feature_181', 'feature_182', 'feature_183', 'feature_184', 'feature_185', 'feature_186', 'feature_187', 'feature_188', 'feature_189', 'feature_190', 'feature_191', 'feature_192', 'feature_193', 'feature_194', 'feature_195', 'feature_196', 'feature_197', 'feature_198', 'feature_199', 'feature_200', 'feature_201', 'feature_202', 'feature_203', 'feature_204', 'feature_205', 'feature_206', 'feature_207', 'feature_208', 'feature_209', 'feature_210', 'feature_211', 'feature_212', 'feature_213', 'feature_214', 'feature_215', 'feature_216', 'feature_217', 'feature_218', 'feature_219', 'feature_220', 'feature_221', 'feature_222', 'feature_223', 'feature_224', 'feature_225', 'feature_226', 'feature_227', 'feature_228', 'feature_229', 'feature_230', 'feature_231', 'feature_232', 'feature_233', 'feature_234', 'feature_235', 'feature_236', 'feature_237', 'feature_238', 'feature_239', 'feature_240', 'feature_241', 'feature_242', 'feature_243', 'feature_244', 'feature_245', 'feature_246', 'feature_247', 'feature_248', 'feature_249', 'feature_250', 'feature_251', 'feature_252', 'feature_253', 'feature_254', 'feature_255', 'feature_256']

In [ ]:
print(train.shape)
train.describe()

(28520, 260)

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_251,feature_252,feature_253,feature_254,feature_255,feature_256,label_1,label_2,label_3,label_4
count,28520.000000,28520.000000,28520.000000,28520.000000,28520.000000,28520.000000,28520.000000,28520.000000,28520.000000,28520.000000,...,28520.000000,28520.000000,28520.000000,28520.000000,28520.000000,28520.000000,28520.000000,28040.000000,28520.000000,28520.000000
mean,-0.225478,-0.616421,-0.212878,0.336330,0.105467,-0.339634,-0.201756,0.742262,0.942325,-1.957584,...,-0.028098,0.296340,1.724439,-1.476765,0.687445,-1.563062,30.498843,27.975107,0.799299,5.997125
std,0.990632,1.005573,1.075468,1.248919,0.831132,1.073267,0.943505,1.055721,0.940459,0.876939,...,0.989497,1.173378,0.968611,1.032811,1.028328,1.243758,17.328389,5.735913,0.400532,2.375567
min,-4.023911,-5.582544,-4.679888,-4.284380,-3.010300,-5.034355,-4.355222,-3.806574,-2.922614,-5.203347,...,-3.679602,-3.905801,-3.301683,-5.490267,-3.810144,-6.056032,1.000000,22.000000,0.000000,0.000000
25%,-0.869656,-1.287018,-0.913419,-0.478661,-0.437171,-1.075753,-0.823699,0.064072,0.298269,-2.556436,...,-0.692262,-0.550897,1.121631,-2.130906,-0.008394,-2.404028,15.000000,25.000000,1.000000,6.000000
50%,-0.190790,-0.609782,-0.218800,0.295881,0.117310,-0.329571,-0.193263,0.755193,0.940786,-1.949847,...,-0.018218,0.295523,1.783432,-1.449978,0.639575,-1.650610,30.000000,27.000000,1.000000,6.000000
75%,0.457509,0.063174,0.490262,1.119242,0.657941,0.393339,0.417146,1.461846,1.579200,-1.345999,...,0.644112,1.128566,2.383575,-0.799414,1.347263,-0.805710,46.000000,30.000000,1.000000,6.000000
max,4.322171,3.876604,4.267163,5.828656,3.884939,3.890622,3.799406,4.817545,4.615069,1.147192,...,3.915582,4.458014,5.261775,2.861117,5.531152,3.338544,60.000000,61.000000,1.000000,13.000000

In [ ]:
print(valid.shape)
valid.describe()

(750, 260)

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_251,feature_252,feature_253,feature_254,feature_255,feature_256,label_1,label_2,label_3,label_4
count,750.000000,750.000000,750.000000,750.000000,750.000000,750.000000,750.000000,750.000000,750.000000,750.000000,...,750.000000,750.000000,750.000000,750.000000,750.000000,750.000000,750.000000,736.000000,750.000000,750.000000
mean,-0.215982,-0.623504,-0.291264,0.377151,0.178972,-0.252002,-0.228841,0.771239,0.922442,-1.959988,...,-0.051848,0.342457,1.691002,-1.485593,0.691309,-1.567317,30.085333,28.330163,0.810667,6.117333
std,0.956326,1.035303,1.128986,1.244136,0.843049,1.069149,0.955363,1.074252,0.947518,0.868173,...,0.987202,1.141813,0.938246,1.051536,1.004137,1.268333,17.489060,6.518500,0.392035,2.227895
min,-3.600761,-5.998218,-3.933543,-3.788818,-2.352740,-4.067048,-3.307670,-3.230605,-2.501911,-4.732800,...,-2.942192,-2.858132,-1.695706,-4.781263,-2.499728,-5.805717,1.000000,22.000000,0.000000,0.000000
25%,-0.834711,-1.307291,-0.998405,-0.422144,-0.424725,-0.992993,-0.916115,0.110733,0.323182,-2.508483,...,-0.716455,-0.491588,1.049466,-2.149493,0.035928,-2.459352,15.000000,25.000000,1.000000,6.000000
50%,-0.205673,-0.607260,-0.307802,0.326517,0.190352,-0.196757,-0.212617,0.816087,0.910706,-1.918432,...,-0.031057,0.333020,1.772243,-1.503996,0.620206,-1.634017,29.000000,27.000000,1.000000,6.000000
75%,0.417797,0.030387,0.412266,1.156195,0.757207,0.476947,0.429078,1.482462,1.535642,-1.396017,...,0.617642,1.135099,2.372264,-0.847414,1.324276,-0.752141,45.000000,30.000000,1.000000,6.000000
max,2.302163,2.441009,3.116088,4.058463,2.861698,2.790602,3.414155,4.249192,3.708912,0.418425,...,3.356440,3.532709,3.927659,2.039558,4.018772,2.496667,60.000000,61.000000,1.000000,13.000000

In [ ]:
print(test.shape)
test.describe()

(750, 260)

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_251,feature_252,feature_253,feature_254,feature_255,feature_256,label_1,label_2,label_3,label_4
count,750.000000,750.000000,750.000000,750.000000,750.000000,750.000000,750.000000,750.000000,750.000000,750.000000,...,750.000000,750.000000,750.000000,750.000000,750.000000,750.000000,0.0,0.0,0.0,0.0
mean,-0.248243,-0.585421,-0.261300,0.292129,0.106505,-0.327901,-0.186109,0.746488,0.896069,-1.999506,...,0.064154,0.279551,1.792623,-1.468001,0.617542,-1.543454,NaN,NaN,NaN,NaN
std,1.007230,1.031605,1.088193,1.275657,0.820163,1.055800,0.937663,1.038833,0.912043,0.865403,...,0.978063,1.150581,0.962225,1.002188,0.999210,1.202299,NaN,NaN,NaN,NaN
min,-3.338338,-5.240058,-3.552587,-3.875104,-2.599635,-3.934916,-2.964872,-2.428432,-2.603179,-4.547704,...,-3.547722,-3.188699,-1.288992,-4.936862,-2.188391,-5.697614,NaN,NaN,NaN,NaN
25%,-0.889425,-1.284925,-1.045593,-0.595757,-0.447941,-1.082658,-0.789457,0.097839,0.294905,-2.604528,...,-0.563641,-0.552616,1.203707,-2.110703,-0.072770,-2.341033,NaN,NaN,NaN,NaN
50%,-0.219966,-0.558214,-0.228610,0.242556,0.114963,-0.293032,-0.200180,0.743686,0.903759,-2.022947,...,0.036205,0.250225,1.887835,-1.454391,0.549354,-1.593112,NaN,NaN,NaN,NaN
75%,0.432476,0.144174,0.433977,1.086600,0.621324,0.401023,0.429726,1.483986,1.515494,-1.431881,...,0.742721,1.074692,2.446600,-0.809374,1.284066,-0.785415,NaN,NaN,NaN,NaN
max,2.788072,2.412955,3.071344,4.845111,3.024339,2.596057,3.295141,4.404866,3.434419,0.694695,...,3.257086,3.445455,4.506212,1.633000,4.192348,2.523189,NaN,NaN,NaN,NaN

Preprocessing the data

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28520 entries, 0 to 28519
Columns: 260 entries, feature_1 to label_4
dtypes: float64(257), int64(3)
memory usage: 56.6 MB

In [ ]:
train[train['label_3'].notna()].shape

(28520, 260)

In [ ]:
train['label_4'].value_counts()

6     19938
2      1449
0       955
12      954
7       938
13      482
1       481
11      480
10      480
3       479
5       478
9       472
4       469
8       465
Name: label_4, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler

tr_df = train
vl_df = valid
tst_df = test

scaler = StandardScaler()

X_train = pd.DataFrame(scaler.fit_transform(tr_df.drop(LABELS, axis = 1)), columns = FEATURES)
Y_train = tr_df['label_1']
X_valid = pd.DataFrame(scaler.transform(vl_df.drop(LABELS, axis = 1)), columns = FEATURES)
Y_valid = vl_df['label_1']

X_test = pd.DataFrame(scaler.transform(tst_df.drop(LABELS, axis = 1)), columns = FEATURES)

In [ ]:
X_train

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_247,feature_248,feature_249,feature_250,feature_251,feature_252,feature_253,feature_254,feature_255,feature_256
0,-1.719486,0.323086,1.226266,1.388683,0.664613,-0.308695,-0.812392,-0.655816,0.179515,0.140254,...,2.113138,1.527554,-0.982967,0.855748,-0.670494,-1.234800,-1.324892,-0.017108,-1.003996,0.938640
1,-1.497857,-0.390408,1.087442,3.184804,-0.932385,2.113584,0.386127,-0.558954,1.503739,-1.073030,...,1.368482,-0.911968,-2.100238,-0.073337,-0.646944,-0.706550,-1.624288,-0.387415,0.937548,-0.919349
2,-1.696629,0.257429,-0.436794,3.455455,-1.191656,1.396831,1.649450,-2.059777,1.294943,-1.389119,...,0.363484,0.440210,-2.993112,-0.249982,0.001384,0.122782,1.054587,0.770736,-1.294388,-0.823439
3,0.932099,-1.593295,-0.334127,0.685190,0.269621,1.007221,1.233836,0.237993,2.078308,0.407337,...,1.087123,-0.112537,-3.350270,-0.846158,0.744967,0.439564,-0.690871,0.543678,-1.567913,0.196262
4,-1.768010,0.119449,0.540221,2.725170,-0.285790,1.467148,-0.317170,0.131942,0.732225,-2.162524,...,1.398393,-0.132943,-1.811507,0.497713,-0.577680,-1.125974,0.150025,-0.989360,2.509757,0.165997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28515,0.093076,1.607867,-0.201254,-0.017915,3.488325,-0.084209,-1.277312,0.247766,1.599102,0.786603,...,0.870184,-0.189773,-0.642649,1.728059,0.776254,-1.112233,-0.875752,1.217201,0.705901,0.498509
28516,1.663375,-0.711944,0.061733,-0.060080,0.384315,-0.358914,1.009997,-2.121422,-0.189213,0.138299,...,0.884920,-0.563606,0.004032,1.218849,-0.162391,0.056092,-0.136669,-0.365558,1.144407,-0.433992
28517,1.371444,-0.016175,0.146018,0.348439,1.420678,0.295186,0.320466,-0.038330,0.285876,0.876290,...,0.412954,-0.219770,-0.461239,-1.311420,1.158437,-2.007156,1.070300,1.827668,-0.329699,-0.336336
28518,-0.776721,-0.005011,0.006696,-0.817254,1.184843,-0.796913,0.179448,-1.120960,0.272548,-0.995704,...,0.591453,0.445483,0.912035,0.320850,0.740111,-0.623250,0.172330,-0.197340,-1.414820,-0.166887
28519,1.057490,-0.271512,0.594492,-0.589436,1.280568,-0.614149,0.800556,1.231810,-1.392186,2.146935,...,0.065703,-0.093213,-1.694447,-0.553324,1.324773,-1.164362,1.450697,1.649844,-0.078958,-1.675530

In [ ]:
Y_train

0        45
1        45
2        45
3        45
4        45
         ..
28515    39
28516    39
28517    39
28518    39
28519    39
Name: label_1, Length: 28520, dtype: int64

In [ ]:
X_train.describe()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_247,feature_248,feature_249,feature_250,feature_251,feature_252,feature_253,feature_254,feature_255,feature_256
count,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04,...,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04,2.852000e+04
mean,3.986215e-18,1.993107e-17,1.993107e-17,1.195864e-17,-1.594486e-17,-1.195864e-17,1.993107e-17,1.195864e-17,-6.377943e-17,2.391729e-17,...,-3.986215e-18,-4.982768e-17,9.566915e-17,6.975875e-17,2.391729e-17,-1.195864e-17,-7.374497e-17,-9.566915e-17,-6.377943e-17,-1.993107e-17
std,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00,...,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00,1.000018e+00
min,-3.834422e+00,-4.938687e+00,-4.153624e+00,-3.699833e+00,-3.748887e+00,-4.374312e+00,-4.402243e+00,-4.308826e+00,-4.109704e+00,-3.701305e+00,...,-4.054992e+00,-3.973555e+00,-4.256645e+00,-4.150868e+00,-3.690328e+00,-3.581297e+00,-5.189090e+00,-3.886065e+00,-4.373767e+00,-3.612478e+00
25%,-6.502805e-01,-6.668919e-01,-6.513943e-01,-6.525690e-01,-6.529014e-01,-6.858795e-01,-6.591950e-01,-6.424065e-01,-6.848443e-01,-6.829011e-01,...,-6.979189e-01,-6.740037e-01,-6.362087e-01,-6.803694e-01,-6.712256e-01,-7.220621e-01,-6.223533e-01,-6.333705e-01,-6.766814e-01,-6.761615e-01
50%,3.501709e-02,6.602356e-03,-5.506804e-03,-3.238791e-02,1.424942e-02,9.376448e-03,9.001863e-03,1.224833e-02,-1.636495e-03,8.823296e-03,...,-4.201522e-02,2.659437e-02,4.476444e-02,5.029245e-04,9.984643e-03,-6.966865e-04,6.090572e-02,2.593739e-02,-4.655127e-02,-7.039145e-02
75%,6.894582e-01,6.758403e-01,6.538103e-01,6.268827e-01,6.647358e-01,6.829483e-01,6.559725e-01,6.816160e-01,6.772076e-01,6.974210e-01,...,6.635117e-01,6.890961e-01,6.712363e-01,6.929655e-01,6.793566e-01,7.092681e-01,6.805080e-01,6.558442e-01,6.416535e-01,6.089327e-01
max,4.590737e+00,4.468203e+00,4.165740e+00,4.397741e+00,4.547456e+00,3.941547e+00,4.240817e+00,3.860258e+00,3.905338e+00,3.540530e+00,...,3.846998e+00,4.017919e+00,3.558372e+00,3.890257e+00,3.985610e+00,3.546808e+00,3.652031e+00,4.200146e+00,4.710357e+00,3.941033e+00

### Now lets check the accuracy of prediction before feature engineering for label 1. Then let's predict the test dataset label value before feature engineering.

**Label 1 - Speaker Id**

In [ ]:
from sklearn import svm, metrics

In [ ]:
model = svm.SVC(kernel = 'linear')
model.fit(X_train, Y_train)
y_pred = model.predict(X_valid)

In [ ]:
print(metrics.confusion_matrix(Y_valid ,y_pred))
print(metrics.accuracy_score(Y_valid ,y_pred))
print(metrics.precision_score(Y_valid ,y_pred, average = 'weighted'))
print(metrics.recall_score(Y_valid ,y_pred, average = 'weighted'))

[[13  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 19  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
0.9906666666666667
0.9914608132608133
0.9906666666666667

In [ ]:
print(metrics.classification_report(Y_valid, y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         9
           3       1.00      1.00      1.00        12
           4       1.00      1.00      1.00        16
           5       1.00      1.00      1.00        18
           6       1.00      1.00      1.00         9
           7       0.94      1.00      0.97        17
           8       1.00      1.00      1.00        14
           9       1.00      1.00      1.00        11
          10       0.89      1.00      0.94         8
          11       1.00      1.00      1.00        19
          12       1.00      1.00      1.00         7
          13       1.00      1.00      1.00        11
          14       1.00      0.93      0.97        15
          15       1.00      1.00      1.00        17
          16       1.00      1.00      1.00        14
          17       1.00      1.00      1.00        14
          18       1.00      1.00      1.00        19
          19       1.00      1.00      1.00        15
          20       1.00      1.00      1.00        11
          21       0.93      1.00      0.97        14
          22       1.00      1.00      1.00        11
          23       0.91      1.00      0.95        10
          24       0.92      1.00      0.96        12
          25       1.00      0.91      0.95        11
          26       1.00      1.00      1.00         7
          27       1.00      0.94      0.97        16
          28       1.00      1.00      1.00        11
          29       1.00      1.00      1.00        15
          30       1.00      1.00      1.00         8
          31       1.00      1.00      1.00        12
          32       1.00      1.00      1.00         9
          33       1.00      1.00      1.00         6
          34       1.00      1.00      1.00        13
          35       1.00      1.00      1.00         8
          36       1.00      1.00      1.00        18
          37       1.00      1.00      1.00        16
          38       0.92      1.00      0.96        11
          39       1.00      1.00      1.00        13
          40       1.00      0.92      0.96        12
          41       1.00      1.00      1.00        10
          42       1.00      1.00      1.00        12
          43       1.00      1.00      1.00        12
          44       1.00      0.95      0.97        19
          45       1.00      1.00      1.00        14
          46       1.00      1.00      1.00        11
          47       0.89      1.00      0.94         8
          48       1.00      1.00      1.00        17
          49       1.00      1.00      1.00        13
          50       1.00      1.00      1.00        13
          51       1.00      1.00      1.00         8
          52       1.00      1.00      1.00        11
          53       1.00      1.00      1.00        15
          54       1.00      0.89      0.94         9
          55       1.00      1.00      1.00         8
          56       1.00      1.00      1.00        10
          57       1.00      1.00      1.00        18
          58       1.00      0.95      0.97        20
          59       1.00      1.00      1.00        10
          60       1.00      1.00      1.00        10

    accuracy                           0.99       750
   macro avg       0.99      0.99      0.99       750
weighted avg       0.99      0.99      0.99       750

The value for label 1 (Speaker ID) for the test dataset is predicted as follows.

In [ ]:
test_pred_before = model.predict(X_test)
df = pd.DataFrame(test_pred_before, columns=['label_1'])
print(df)
df.to_csv('predicted_label_1_before_feature_engineering.csv', index=False)

     label_1
0         45
1         45
2         45
3         45
4         45
..       ...
745       39
746       39
747       39
748       39
749       39

[750 rows x 1 columns]

### Feature Engineering

PCA

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components= 0.95, svd_solver= 'full')
pca.fit(X_train)
X_train_after_pca = pd.DataFrame(pca.transform(X_train))
X_valid_after_pca = pd.DataFrame(pca.transform(X_valid))
X_test_after_pca = pd.DataFrame(pca.transform(X_test))
print(X_train_after_pca.shape)

(28520, 67)

In [ ]:
model_after_pca = svm.SVC(kernel = 'linear')
model_after_pca.fit(X_train_after_pca, Y_train)
y_pred_after_pca = model_after_pca.predict(X_valid_after_pca)
print(metrics.confusion_matrix(Y_valid,y_pred_after_pca))
print(metrics.accuracy_score(Y_valid,y_pred_after_pca))
print(metrics.precision_score(Y_valid,y_pred_after_pca, average = 'weighted'))
print(metrics.recall_score(Y_valid,y_pred_after_pca, average = 'weighted'))

[[12  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
0.9813333333333333
0.9835733337182255
0.9813333333333333

Test data is predicted here

In [ ]:
test_pred_after_pca = model_after_pca.predict(X_test_after_pca)
df_after = pd.DataFrame(test_pred_after_pca, columns=['label_1'])
print(df_after)
df_after.to_csv('predicted_label_1_after_feature_engineering.csv', index=False)

     label_1
0         45
1         45
2         45
3         45
4         45
..       ...
745       39
746       39
747       39
748       39
749       39

[750 rows x 1 columns]

Getting the csv files after feature engineering

In [ ]:
NEW_COLUMNS = ['New_feature_'+ str(i) for i in range(1,68)]
X_test_df_after = pd.DataFrame(X_test_after_pca)
print(X_test_df_after)
X_test_df_after.to_csv('new_features_label_1.csv', index=False)

            0         1         2          3         4         5         6   \
0    -1.967567  6.945703 -3.947321  -1.108198 -6.440248 -1.053785  3.471608
1    -6.692310  8.884467 -0.489867 -10.240206 -4.576115  2.229018 -2.025519
2    -4.810155  3.547653 -0.297522  -5.550987 -2.225314 -1.305231 -0.434514
3    -2.185614  5.993099 -1.089448  -0.938549  2.566186  4.411621  0.475160
4     0.695696  6.181181  1.442544  -3.112025 -2.881196 -1.171098  1.626019
..         ...       ...       ...        ...       ...       ...       ...
745   0.370687 -1.536461 -7.516708   4.317870  0.249244 -3.122142  0.695939
746  11.165413  4.127378 -1.536515  -0.896263 -0.214402  0.636541  0.736327
747  -5.593004  2.172272 -2.118896  -1.539570  2.049187  4.802564 -5.281143
748  -4.349980  3.831893  3.496943   3.157099 -2.192043 -0.095471 -0.314058
749   3.170687  2.672466 -4.072233   1.804944 -6.341352 -2.078463 -1.671187

           7         8         9   ...        57        58        59  \
0    2.685400  5.946839  2.065199  ...  0.578949 -1.740188 -0.118466
1    2.366489 -2.672080  7.428873  ... -0.430111  1.420051 -0.984095
2   -0.250999 -5.807706  4.932742  ... -0.623699 -0.565450 -0.924432
3    0.404839  1.420231  6.211550  ...  0.828342 -0.924356  0.728764
4    3.521929  0.719271  7.522156  ... -0.643171  0.046833 -0.774574
..        ...       ...       ...  ...       ...       ...       ...
745 -3.901204 -1.450829  1.634423  ...  0.236781 -0.759393 -0.505158
746 -1.343028 -0.328976 -2.273540  ... -0.129141 -0.071592 -1.477981
747 -2.319679 -0.896200 -0.440070  ... -1.451143 -0.341196 -0.219249
748 -2.746004  3.591874 -3.471576  ...  0.892938  1.852581  2.269793
749 -0.370265  1.288088  0.675442  ...  0.551602 -0.401927 -0.771040

           60        61        62        63        64        65        66
0    1.373034  1.198465  0.701518 -0.092956 -0.961733 -1.577341  0.453901
1    0.078896 -0.163620  1.022940  1.326354  0.892220 -0.054520 -0.060989
2   -0.114114 -0.526053 -0.612581  0.770387  0.258546 -0.176509 -0.049412
3   -0.928061  0.356018  0.039349 -1.203948  0.575542  1.194812 -0.065328
4    0.500928  0.716768 -0.848316  0.289207  1.111349  0.781681  0.461655
..        ...       ...       ...       ...       ...       ...       ...
745  0.090786  0.074509  0.502837 -1.595285 -0.045266 -0.513792 -0.333688
746  0.068463  0.227283 -0.911562  0.485611 -0.120087  0.357190  0.317572
747  0.303167  1.290557 -0.329881  1.050533  1.357782  0.317508 -0.216969
748 -0.129378 -0.452473 -0.081809 -0.695154 -0.143859  1.293518  1.104163
749  0.933634 -0.264049  0.065744 -1.006082  0.162721 -1.185616 -0.300455

[750 rows x 67 columns]